#!/bin/sh

OUT="testdata/pki"
CRT="$OUT/ca.crt"
KEY="$OUT/ca.key"

openssl ecparam -name prime256v1 -genkey -noout -out "$KEY"

openssl req -new -x509 -sha256 \
    -subj '/CN=ZTCA' \
    -addext 'keyUsage = keyCertSign, cRLSign' \
    -key "$KEY" \
    -out "$CRT"
